##生产环境
server:
  port: 8080
  address: 0.0.0.0
  servlet:
    context-path: /hkexpress
##thymeleaf页面模板配置
web:
  upload-path: C:/faqsonic/faq

spring:
  data:
    elasticsearch:
      repositories:
        enabled: true
      cluster-name: elasticsearch
      cluster-nodes: 127.0.0.1:9300
      properties:
        path:
          logs: ./elasticsearch/log
          data: ./elasticsearch/data
      local: true
  # 多个springboot项目部署,需加
  jmx:
    enabled: false
  #jpa配置
  jpa:
    database: mysql
    show-sql: false
    hibernate:
      ddl-auto: none
  tomcat:
    uri-encoding: UTF-8
  datasource:
    ## 118.143.2.10
    url: jdbc:mysql://118.143.2.10:3306/faqsDate208?characterEncoding=UTF-8
    username: root
    password: sonic@xunyu
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      read-only: false
      connection-timeout: 60000
      idle-timeout: 60000
      validation-timeout: 3000
      max-lifetime: 60000
      login-timeout: 5
      maximum-pool-size: 60
      minimum-idle: 10
  mvc:
    static-path-pattern: /**
  thymeleaf:
    cache: false
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${web.upload-path}
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0
      #单个数据的大小
      max-file-size: 80Mb
      #总数据的大小
      max-request-size: 200Mb
  # JavaMailSender 邮件发送的配置
  mail:
    host: mail.sonic-teleservices.com
    username: hke_smartform@sonic-teleservices.com
    password: sonic
    default-encoding: UTF-8
    properties:
      mail.smtp.socketFactory.fallback: true
      mail.smtp.starttls.enable: false
    port: 11125
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.example.demo.bean
  configuration:
    map-underscore-to-camel-case: true