##测试环境
server:
  port: 8080
  address: 0.0.0.0
  ##servlet:
    ##context-path: /faqs
##thymeleaf页面模板配置
web:
  upload-path: C:/faqsonic/faq

spring:
  #jpa配置
  jpa:
    database: mysql
    show-sql: false
    hibernate:
      ddl-auto: none
  tomcat:
    uri-encoding: UTF-8
  datasource:
    url: jdbc:mysql://118.143.2.3:3306/faqsdatetest?characterEncoding=UTF-8
    username: root
    password: sonic@xunyu
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${web.upload-path}
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0
      #单个数据的大小
      max-file-size: 80Mb
      #总数据的大小
      max-request-size: 200Mb
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.example.demo.bean
  configuration:
    map-underscore-to-camel-case: true